# Jekyll config
markdown: redcarpet
exclude:  [ Gemfile, Gemfile.lock, scss/, README.md, config.rb, bower.json, bin/, bower_components/, .sass-cache/, vendor/ ]

# Website config
title:      "Planet Clermont'ech"
headline:   "Retrouvez tous les événements du monde IT Auvergnat !"
footer:
    Planet Clermont'ech regroupe l'ensemble des acteurs du monde IT Auvergnat à
    travers un agenda ouvert et accessible, présentant les événements régionaux.
    Vous souhaitez publier votre événement ? Vous pouvez passer par
    [GitHub](https://github.com/clermontech/planet#clermontech-planet) ou
    envoyer un email à [planet@clermontech.org](mailto:planet@clermontech.org).

meta:
    default_author:         "Clermont'ech et al."
    default_description:    ""
    email:                  "planet@clermontech.org"

base_url: "http://planet.clermontech.org"

google:
    analytics:              "UA-41697057-2"

insert:
    google-calendar:        "Ajouter à mon agenda Google"
    icalendar:              "Ajouter à mon agenda (.ics)"


tags:
    url: /tags/
    title_prefix: ""
    layout: tag.html
